export { default as Home } from './Home'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as ServiceDetail } from './ServiceDetail'
export { default as Gallery } from './Gallery'
export { default as Testimonials } from './Testimonials'
export { default as Contact } from './Contact'
export { default as NotFound } from './NotFound'
